### PR TITLE
All examples cleaned up

### LINKED ISSUE #5: Delete all of the "example" template code
Ticket Template
**Summary**
When you make a new project, WPILib starts you off with some example code that you never end up using, to create a template for you. We aren't going to use it, so delete it. This is a good issue to practice our software development process with. Also, we don't need the constants file, as we shall be using TOML to store all of our robot constants.

**Work Required**
 - remove "ExampleSubsystem.h"
 - remove "ExampleSubsystem.cpp"
 - remove "ExampleCommand.h"
 - remove "ExampleCommand.cpp"
 - remove "Constants.h"
 - fix RobotContainer so the code builds

**Verification**
 - all example files removed
 - CI passes

### PR DESCRIPTION
**Pull request by deadlyvortex**
closes #5

### CODE REVIEW

**Review by jkleiber — CHANGES_REQUESTED** [review]
This will fail to compile because GetAutonomousCommand needs to be modified to return `nullptr` or something instead of `m_autonomousCommand`

**Comment by deadlyvortex** [comment]
do i have to change robotcontainer.h

**Review by jkleiber — APPROVED** [review]
looks good to me, just need to rebase

**Review by jkleiber — APPROVED** [review]
LGTM

**Comment by danielbrownmsm** [comment]
why does it say I did stuff what

**Comment by jkleiber** [comment]
Because you were logged in to git for whatever computer Sai was using

**Pull request merged**
